#include "decoder.h"     // Links this file to your decoder blueprints
#include "math_engine.h" // Gives you access to your matrix multiplication functions
#include <cstdint>       // Ensures type safety for your 8-bit integer bytes (uint8_t)
// TOP CODE GENERATED BY AI LOLL :3



uint8_t removePermutation(uint8_t noisyCiphertext, const uint8_t* privatePInv) {
    uint8_t cipherVec = noisyCiphertext & 0x7F;
    return vectorMatrixMultiply(cipherVec, privatePInv, 7, 7);
}

//#include <iostream> // For debug output

uint8_t cleanRadioNoise(uint8_t unshuffledBlock, const uint8_t* privateG) {
    uint8_t H[7] = {0};

    // 1. Copy the 3 parity bits from the right side of privateG straight into H[0] through H[3]
    for (int r = 0; r < 4; r++) {
        H[r] = privateG[r] & 0x07;
    }

    // 2. Append the standard 3x3 Identity Block to complete the 7x3 system
    H[4] = 0b100;
    H[5] = 0b010;
    H[6] = 0b001;

    uint8_t cipherVec = unshuffledBlock & 0x7F;

    // 3. Compute the 3-bit syndrome vector using your math engine
    uint8_t syndrome = vectorMatrixMultiply(cipherVec, H, 7, 3);

    // If syndrome is 0, no bit flips occurred!
    if (syndrome == 0) {
        return unshuffledBlock;
    }

    // 4. Scan down rows 0 to 6 to find the unique index that matches the signature
    int errorColumn = -1;
    for (int c = 0; c < 7; c++) {
        if (H[c] == syndrome) {
            errorColumn = c;
            break;
        }
    }

    // 5. Flip the exact corrupted bit position
    if (errorColumn != -1) {
        unshuffledBlock ^= (1 << (6 - errorColumn));
    }

    // std::cout << "[DEBUG] UnshuffledBlock layout:\n";
    // for (int r = 0; r < 7; r++) {
    //     std::cout << "  Row " << r << ": ";
    //     for (int b = 6; b >= 0; b--) {
    //         std::cout << ((unshuffledBlock >> b) & 1);
    //     }
    //     std::cout << "\n";
    // }
    // std::cout << "\n";

    return unshuffledBlock;
}



uint8_t removeScrambler(uint8_t cleanBlock, const uint8_t* privateSInv) {
    uint8_t coreDataBits = (cleanBlock >> 3) & 0x0F;
    return vectorMatrixMultiply(coreDataBits, privateSInv, 4, 4);
}