#include "key_gen.h"
#include "math_engine.h"
#include <algorithm>
#include <random>
#include <cstdint>

void generatePublicKey(const uint8_t* privateG, const uint8_t* privateP, const uint8_t* privateS, uint8_t* publicMatrix) {
    uint8_t intermediate_S_times_G[K_ROWS] = {0};
    for(int i = 0; i < 4; i++) publicMatrix[i] = 0; // Clear out the matrix for safety or smth idk :3
    matrixMultiply(privateS, privateG, intermediate_S_times_G, 4, 4, 7);
    matrixMultiply(intermediate_S_times_G, privateP, publicMatrix, 4, 7, 7);
}

void generateRandomGenerator(uint8_t* privateG) { // Function generated by AI nauururrururru :c
    std::random_device rd;
    std::mt19937 g(rd());
    std::uniform_int_distribution<> dis(0, 1);

    while (true) {
        // 1. Generate the standard random systematic matrix layout
        for (int r = 0; r < 4; r++) {
            privateG[r] = 0;
            privateG[r] |= (1 << (6 - r)); // Left 4 bits Identity Matrix
            
            for (int c = 4; c < 7; c++) {
                if (dis(g)) {
                    privateG[r] |= (1 << (6 - c)); // Right 3 bits Parity Matrix
                }
            }
        }

        // 2. Extract the resulting H rows to check for cryptographic viability
        uint8_t hRows[7];
        for (int r = 0; r < 4; r++) hRows[r] = privateG[r] & 0x07;
        hRows[4] = 0b100;
        hRows[5] = 0b010;
        hRows[6] = 0b001;

        // 3. Cryptographic Validation: Ensure all 7 rows are unique and non-zero
        bool matrixIsValid = true;
        for (int i = 0; i < 7; i++) {
            if (hRows[i] == 0) {
                matrixIsValid = false; // All-zero rows create dead zones
                break;
            }
            for (int j = i + 1; j < 7; j++) {
                if (hRows[i] == hRows[j]) {
                    matrixIsValid = false; // Duplicate signatures cause ambiguity
                    break;
                }
            }
            if (!matrixIsValid) break;
        }

        // If the matrix passes all security validation checks, lock it in!
        if (matrixIsValid) {
            break;
        }
    }
}




void generateRandomPermutation(uint8_t* privateP) {
    int columns[7] = {0, 1, 2, 3, 4, 5, 6};

    std::random_device rd;
    std::mt19937 g(rd());
    std::shuffle(std::begin(columns), std::end(columns), g);

    for (int r=0; r<7; r++) {
        privateP[r] = 0;
        privateP[r] |= (1 << (6 - columns[r]));
    }
}


void generateRandomScrambler(uint8_t* privateS) {
    uint8_t L[4] = {0};
    uint8_t U[4] = {0};

    for(int i = 0; i < 4; i++) privateS[i] = 0; // Clear memory for system or smth idk again :3

    //Anyways before this code was modified we was using rand() which is not a modern random engine
    std::random_device rd;
    std::mt19937 g(rd());
    std::uniform_int_distribution<> dis(0, 1);

    /* What we want is [1, 0, 0 ,0] , next row-> [?,1,0,0] and so on creating a diagonal*/
    // Anyways thats how a femboy, trans, coder codes 
    for (int r=0; r<4; r++) {
        for (int c=0; c<4; c++) {
            if (r == c) {
                L[r] |= (1 << (3 - c)); // This will set the main diagonal bit to 1
            } else if (r > c) {
                if (dis(g)) { //  if r which is say row 1 now. and c is lower than r. since this is a Lower Matrix or whatever we want to randomly decide whether if its a 1 or 0
                    L[r] |= (1 << (3 - c));
                }
            }
        }
    }

    for (int r=0; r<4; r++) {
        for (int c=0; c<4; c++) {
            if (r == c) {
                U[r] |= (1 << (3-c));
            } else if (r < c) {
                if (dis(g)) {
                    U[r] |= (1 << (3 - c));
                }
            }
        }
    }

    matrixMultiply(L, U, privateS, 4, 4, 4);

}


void invertPermutationMatrix(const uint8_t* matrixP, uint8_t* inverseP) {
    for (int r = 0; r < 7; r++) {
        inverseP[r] = 0;
        for (int c = 0; c < 7; c++) {
            if ((matrixP[c] >> (6 - r)) & 1) {
                inverseP[r] |= (1 << (6 - c));
            }
        }
    }
}

// IN HONESTY THIS LOWER CODE WAS GENERATED BY AI...... YEAH I GOT LAZY.. I MEAN I DIDNT WASTE TIME
// ALL I DID WAS ASK IT TO GIMME BECAUSE IF I DID IT MYSELF.. WE'D GET THE SAME SITUATION RIGHT?
// LOOK IT EVEN GAVE ME A BOOL SO I CAN SAY THAT INVERSION DID FAIL IN THE RUNTIME
bool invertScramblerMatrix(const uint8_t* matrixS, uint8_t* inverseS) {
    uint8_t left[4];
    uint8_t right[4] = {0b1000, 0b0100, 0b0010, 0b0001};
    
    for (int i = 0; i < 4; i++) {
        left[i] = matrixS[i] & 0x0F;
        inverseS[i] = 0;
    }

    for (int c = 0; c < 4; c++) {
        int pivotRow = -1;
        for (int r = c; r < 4; r++) {
            if ((left[r] >> (3 - c)) & 1) {
                pivotRow = r;
                break;
            }
        }

        if (pivotRow == -1) {
            return false; 
        }

        if (pivotRow != c) {
            std::swap(left[c], left[pivotRow]);
            std::swap(right[c], right[pivotRow]);
        }

        for (int r = 0; r < 4; r++) {
            if (r != c) {
                if ((left[r] >> (3 - c)) & 1) {
                    left[r] ^= left[c];
                    right[r] ^= right[c];
                }
            }
        }
    }

    for (int i = 0; i < 4; i++) {
        inverseS[i] = right[i];
    }
    
    return true;
}
