/*
 *  Project: M78-Chiper
 *  Author: InternecionCrystal0n
 *  
 *  Description: Post Quantum Cipher based on McEliece Cryptosystem. 
 *  Also inspired by QR Codes and the error correction to prevent Quantum.
 *  This system is Assymetric therefore it is a shoot and forget system.
 * 
 *  Credits: Based on the mathematical foundations of the McEliece Cryptosystem 
 *  invented by Robert McEliece in 1978.
 * 
 *  Usage of AI: This project is assited by AI for debugging and review and only the header files were generated by AI. The usage of AI was very limited and the ideas were still made by human. 
 *  AI only helped with research and debugging and header files.
*/

// AI GENERATED STRUCTURE BUT I MODIFIED IT ALOT AND FIXED A BUNCH OF FAGGING BUGS ;3

#include <iostream>
#include <vector>
#include <string>
#include <cstdlib>

#include "math_engine.h"
#include "key_gen.h"
#include "encoder.h"
#include "decoder.h"

uint8_t privateG[4] = {0};
uint8_t privateP[7] = {0};
uint8_t privateS[4] = {0};
uint8_t P_INV[7] = {0};
uint8_t S_INV[4] = {0};

int main() {
    uint8_t publicKey[4] = {0};

    generateRandomGenerator(privateG);
    // std::cout << "[DEBUG] Private G (Decimal format): ";
    // for (int r = 0; r < 4; r++) {
    //     std::cout << static_cast<int>(privateG[r]) << " ";
    // }
    // std::cout << "\n\n";
    generateRandomPermutation(privateP);
    generateRandomScrambler(privateS);

    generatePublicKey(privateG, privateP, privateS, publicKey);

    bool sM = invertScramblerMatrix(privateS, S_INV);
    if (sM == false) {
        std::cout << "[ERROR] inverting scramble matrix failed... nauurrr exiting the program.." << std::endl;
        return -1;
    }
    invertPermutationMatrix(privateP, P_INV);

    std::cout << "[M78-Cipher] Dynamic Public Key generated successfully.\n" << std::endl;

    std::cout << "WELCOME TO M78-CIPHER. Version: 0.1.0 - THIS IS THE FIRST WORKING PROTOTYPE" << std::endl;

    std::string userInput;
    std::cout << "Input to Encrypt; \n>> ";
    std::getline(std::cin, userInput);

    if (userInput.empty()) {
        std::cout << "[ERROR] The input cannot be empty. Exiting the program..." << std::endl;
        return 1;
    }

    std::cout << "\n[M78-Cipher] Encrypting " << userInput.length() << " characters..." << std::endl;

    // THIS IS A SIMULATION THEREFORE IT USES AIR WAVES
    std::vector<uint8_t> airwaves;

    for (char character : userInput) {
        // Nibbles
        uint8_t highNibble = (character >> 4) & 0x0F;
        uint8_t lowNibble = character & 0x0F;

        uint8_t pureCipherHigh = encryptBlock(highNibble, publicKey);
        uint8_t pureCipherLow = encryptBlock(lowNibble, publicKey);

        uint8_t noisyCipherHigh = injectNoise(pureCipherHigh);
        uint8_t noisyCipherLow = injectNoise(pureCipherLow);

        airwaves.push_back(noisyCipherHigh);
        airwaves.push_back(noisyCipherLow);
    }

    std::cout << "[M78-Cipher] Simulating airwaves to transmit the 7 Bits" << std::endl;
    std::cout << "[M78-Cipher Inner] The Raw Cipher Stream (Decimal format): ";
    size_t displayLimit = airwaves.size() > 20 ? 20 : airwaves.size();
    for (size_t i = 0; i < displayLimit; i++) {
        std::cout << (int)airwaves[i] << " ";
    }
    if (airwaves.size() > 20) std::cout << "... [truncated]";
    std::cout << "\n\n" << std::endl;

    std::string decryptedMessage = "";
    
    for (size_t i = 0; i < airwaves.size(); i += 2) {
        uint8_t receivedHigh = airwaves[i];
        uint8_t receivedLow = airwaves[i + 1];

        uint8_t unshuffledHigh = removePermutation(receivedHigh, P_INV);
        uint8_t unshuffledLow = removePermutation(receivedLow, P_INV);

        uint8_t cleanHigh = cleanRadioNoise(unshuffledHigh, privateG);
        uint8_t cleanLow = cleanRadioNoise(unshuffledLow, privateG);

        uint8_t finalHigh = removeScrambler(cleanHigh, S_INV);
        uint8_t finalLow = removeScrambler(cleanLow, S_INV);

        char decryptedChar = (finalHigh << 4) | finalLow;
        decryptedMessage += decryptedChar;
    }

    std::cout << "[M78-Cipher] Decryption Process Complete." << std::endl;
    std::cout << "[M78-Cipher] Decrypted Output Result: " << decryptedMessage << std::endl;
    std::cout << "Exiting Program" << std::endl;

    return 0;
}
